name: Rust ARM Cross Compile

on:
  workflow_dispatch:
  push:
    branches:
      - release

jobs:
  build-arm64:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y gcc-aarch64-linux-gnu

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: aarch64-unknown-linux-gnu
          profile: minimal

      - name: Configure Cargo
        run: |
          sudo apt update
          sudo apt install -y gcc-arm-linux-gnueabihf
          sudo apt install -y libglib2.0-dev
          mkdir -p .cargo
          cat <<EOF > .cargo/config.toml
          [target.arm-unknown-linux-gnueabihf]
          linker = "arm-linux-gnueabihf-gcc"
          EOF

      - name: Install Zig
        run: |
          ZIG_VERSION=0.13.1
          wget https://ziglang.org/download/${ZIG_VERSION}/zig-linux-x86_64-${ZIG_VERSION}.tar.xz
          tar xf zig-linux-x86_64-${ZIG_VERSION}.tar.xz
          sudo mv zig-linux-x86_64-${ZIG_VERSION} /usr/local/zig
          sudo ln -s /usr/local/zig/zig /usr/local/bin/zig

      - name: Verify Zig installation
        run: |
          zig version

      - name: Install cargo-zigbuild
        run: |
          cargo install cargo-zigbuild

      - name: Build with zig
        run: |
          cd src-tauri
          cargo zigbuild --target arm-unknown-linux-gnueabihf --release

      - name: Upload ARM64 binary
        uses: actions/upload-artifact@v4
        with:
          name: arm64-binary
          path: target/aarch64-unknown-linux-gnu/release/your_binary

  build-armv7l:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y gcc-arm-linux-gnueabihf

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: arm-unknown-linux-gnueabihf
          profile: minimal

      - name: Configure Cargo
        run: |
          sudo apt update
          sudo apt install -y gcc-arm-linux-gnueabihf
          sudo apt install -y libglib2.0-dev
          mkdir -p .cargo
          cat <<EOF > .cargo/config.toml
          [target.arm-unknown-linux-gnueabihf]
          linker = "arm-linux-gnueabihf-gcc"
          EOF
      - name: Install Zig
        run: |
          ZIG_VERSION=0.13.1
          wget https://ziglang.org/download/${ZIG_VERSION}/zig-linux-x86_64-${ZIG_VERSION}.tar.xz
          tar xf zig-linux-x86_64-${ZIG_VERSION}.tar.xz
          sudo mv zig-linux-x86_64-${ZIG_VERSION} /usr/local/zig
          sudo ln -s /usr/local/zig/zig /usr/local/bin/zig

      - name: Verify Zig installation
        run: |
          zig version
      - name: Install cargo-zigbuild
        run: |
          cargo install cargo-zigbuild

      - name: Build with zig
        run: |
          cd src-tauri
          cargo zigbuild --target arm-unknown-linux-gnueabihf --release

      - name: Upload ARMv7 binary
        uses: actions/upload-artifact@v4
        with:
          name: armv7-binary
          path: target/arm-unknown-linux-gnueabihf/release/your_binary
